{
  "intrinsic_params": {
    "fx": 260.8450622558594,
    "fy": 260.8450622558594,
    "cx": 324.6383056640625,
    "cy": 178.55564880371094
  },
  "extrinsic_params": {
    "translation": [1.04, 0.0, 0.84],
    "quaternion": [0.68421587, 0.63428563, -0.22690795, -0.27936206]
  }
}
